#!/usr/bin/env bash
set -euo pipefail

# PM2 can inherit an operator shell containing application credentials.  The
# Gateway itself must receive only its explicit local service contract.
readonly GATEWAY_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
for required in \
  XIANSUO_HERMES_GATEWAY_NODE_BIN \
  ILINK_POC_TRANSPORT ILINK_GATEWAY_HOST ILINK_GATEWAY_PORT \
  ILINK_POC_LIVE_ENABLED ILINK_HERMES_TRANSPORT_ENABLED \
  ILINK_REQUEST_TIMEOUT_MS ILINK_SESSION_CHECK_TIMEOUT_MS \
  ILINK_POC_STATE_DIR ILINK_GATEWAY_SECRET_FILE \
  ILINK_HERMES_PRIVATE_ROOT ILINK_HERMES_SOURCE_DIR ILINK_HERMES_PYTHON ILINK_HERMES_CONFIG_FILE ILINK_HERMES_STATE_DIR; do
  : "${!required:?缺少 Gateway 受控配置 ${required}}"
done
readonly NODE_BIN="$XIANSUO_HERMES_GATEWAY_NODE_BIN"
[[ "$NODE_BIN" = /* && -x "$NODE_BIN" ]] || { echo "Gateway Node 必须为绝对可执行路径" >&2; exit 2; }
readonly SAFE_PATH="${PATH:?PATH 不可用}"

exec /usr/bin/env -i \
  PATH=/usr/bin:/bin \
  LANG="${LANG:-C.UTF-8}" \
  LC_ALL="${LC_ALL:-}" \
  TZ="${TZ:-}" \
  ILINK_POC_TRANSPORT="$ILINK_POC_TRANSPORT" \
  ILINK_GATEWAY_HOST="$ILINK_GATEWAY_HOST" \
  ILINK_GATEWAY_PORT="$ILINK_GATEWAY_PORT" \
  ILINK_POC_LIVE_ENABLED="$ILINK_POC_LIVE_ENABLED" \
  ILINK_HERMES_TRANSPORT_ENABLED="$ILINK_HERMES_TRANSPORT_ENABLED" \
  ILINK_REQUEST_TIMEOUT_MS="$ILINK_REQUEST_TIMEOUT_MS" \
  ILINK_SESSION_CHECK_TIMEOUT_MS="$ILINK_SESSION_CHECK_TIMEOUT_MS" \
  ILINK_POC_STATE_DIR="$ILINK_POC_STATE_DIR" \
  ILINK_GATEWAY_SECRET_FILE="$ILINK_GATEWAY_SECRET_FILE" \
  ILINK_HERMES_SOURCE_DIR="$ILINK_HERMES_SOURCE_DIR" \
  ILINK_HERMES_PYTHON="$ILINK_HERMES_PYTHON" \
  ILINK_HERMES_PRIVATE_ROOT="$ILINK_HERMES_PRIVATE_ROOT" \
  ILINK_HERMES_CONFIG_FILE="$ILINK_HERMES_CONFIG_FILE" \
  ILINK_HERMES_STATE_DIR="$ILINK_HERMES_STATE_DIR" \
  "$NODE_BIN" "$GATEWAY_DIR/dist/server.js"
