module.exports = {
  apps: [{
    name: 'xiansuo-notification-worker',
    script: 'dist/notification-worker.js',
    cwd: process.env.XIANSUO_SERVER_DIR || '/opt/xiansuo/server',
    interpreter: 'node',
    instances: 1,
    exec_mode: 'fork',
    autorestart: true,
    stop_exit_codes: [0],
    env: {
      NODE_ENV: process.env.NODE_ENV || 'production',
      DB_PATH: process.env.DB_PATH,
      LEAD_POOL_CLAIM_ENABLED: process.env.LEAD_POOL_CLAIM_ENABLED || 'false',
      NOTIFICATION_WORKER_ENABLED: process.env.NOTIFICATION_WORKER_ENABLED || 'false',
      NOTIFICATION_CAPTURE_ENABLED: process.env.NOTIFICATION_CAPTURE_ENABLED || 'false',
      NOTIFICATION_MOCK_ENABLED: process.env.NOTIFICATION_MOCK_ENABLED || 'false',
      NOTIFICATION_SCHEDULER_ENABLED: process.env.NOTIFICATION_SCHEDULER_ENABLED || 'false',
      OPENCLAW_CHANNEL_ENABLED: process.env.OPENCLAW_CHANNEL_ENABLED || 'false',
      OPENCLAW_PILOT_USER_ID: process.env.OPENCLAW_PILOT_USER_ID,
      OPENCLAW_GATEWAY_URL: process.env.OPENCLAW_GATEWAY_URL || 'http://127.0.0.1:38115',
      OPENCLAW_GATEWAY_SECRET_FILE: process.env.OPENCLAW_GATEWAY_SECRET_FILE,
      OPENCLAW_GATEWAY_TIMEOUT_MS: process.env.OPENCLAW_GATEWAY_TIMEOUT_MS || '10000',
      OPENCLAW_MAX_ATTEMPTS: process.env.OPENCLAW_MAX_ATTEMPTS || '2',
    },
  }],
};
